"""AI orchestration: payload -> provider -> persisted insight.

Degradation policy, which is the important part of this module: if the provider
fails for any reason, the request still succeeds. The section is regenerated by
:class:`MockProvider` instead, flagged ``is_fallback=True`` and surfaced with a
``degraded_reason``. The dashboard, analytics and exports never depend on the
AI layer being available.
"""

from __future__ import annotations

import uuid
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import AIProviderError, NotFoundError
from app.core.logging import get_logger
from app.models.ai_insight import AIInsight, InsightType
from app.repositories.ai_insight import AIInsightRepository
from app.repositories.analysis_run import AnalysisRunRepository
from app.repositories.organization import OrganizationRepository
from app.schemas.ai import AIPayload, InsightBundle, InsightOut
from app.schemas.analytics import AnalyticsResult
from app.services.ai.factory import get_provider
from app.services.ai.mock import MockProvider
from app.services.ai.payload import build_ai_payload
from app.services.ai.provider import AIProvider, AIResponse

logger = get_logger(__name__)

_SECTIONS: tuple[tuple[InsightType, str], ...] = (
    (InsightType.EXECUTIVE_SUMMARY, "generate_summary"),
    (InsightType.ROOT_CAUSE, "generate_root_cause"),
    (InsightType.RECOMMENDATIONS, "generate_recommendations"),
    (InsightType.RISKS, "generate_risks"),
)


class AIService:
    def __init__(
        self,
        session: AsyncSession,
        organization_id: uuid.UUID,
        *,
        provider: AIProvider | None = None,
    ) -> None:
        self.session = session
        self.organization_id = organization_id
        self.insights = AIInsightRepository(session, organization_id)
        self.runs = AnalysisRunRepository(session, organization_id)
        self.orgs = OrganizationRepository(session)
        self._provider = provider

    @property
    def provider(self) -> AIProvider:
        if self._provider is None:
            self._provider = get_provider()
        return self._provider

    async def generate(
        self,
        analysis_run_id: uuid.UUID,
        *,
        refresh: bool = False,
    ) -> InsightBundle:
        """Generate (or return cached) narrative for an analysis run."""
        run = await self.runs.get(analysis_run_id)
        if run is None:
            raise NotFoundError("Analysis run not found.")
        if run.result is None:
            raise NotFoundError("This analysis run has no stored result to narrate.")

        if refresh:
            await self.insights.delete_for_run(analysis_run_id)
            await self.session.flush()

        existing = {
            insight.insight_type: insight
            for insight in await self.insights.list_for_run(analysis_run_id)
        }
        if not refresh and len(existing) == len(_SECTIONS):
            return self._bundle(analysis_run_id, list(existing.values()))

        result = AnalyticsResult.model_validate(run.result)
        organization = await self.orgs.get(self.organization_id)
        payload = build_ai_payload(
            result, industry=organization.industry if organization else None
        )

        # Persist the exact payload so the privacy boundary stays auditable.
        run.ai_payload = payload.model_dump(mode="json")

        provider = self.provider
        produced: list[AIInsight] = []
        for insight_type, method_name in _SECTIONS:
            if insight_type in existing:
                produced.append(existing[insight_type])
                continue
            response = await self._call_with_fallback(provider, method_name, payload)
            produced.append(await self._persist(analysis_run_id, insight_type, response))

        await self.session.commit()
        return self._bundle(analysis_run_id, produced)

    async def get_bundle(self, analysis_run_id: uuid.UUID) -> InsightBundle | None:
        insights = await self.insights.list_for_run(analysis_run_id)
        if not insights:
            return None
        return self._bundle(analysis_run_id, insights)

    async def build_payload_for_run(self, analysis_run_id: uuid.UUID) -> AIPayload:
        """Exposed for the ``/ai/payload`` transparency endpoint."""
        run = await self.runs.get(analysis_run_id)
        if run is None or run.result is None:
            raise NotFoundError("Analysis run not found.")
        organization = await self.orgs.get(self.organization_id)
        return build_ai_payload(
            AnalyticsResult.model_validate(run.result),
            industry=organization.industry if organization else None,
        )

    # -- internals ----------------------------------------------------------
    async def _call_with_fallback(
        self, provider: AIProvider, method_name: str, payload: AIPayload
    ) -> AIResponse:
        method: Callable[[AIPayload], Awaitable[AIResponse]] = getattr(provider, method_name)
        try:
            return await method(payload)
        except AIProviderError as exc:
            logger.warning(
                "ai_section_degraded",
                extra={"section": method_name, "reason": exc.message},
            )
        except Exception as exc:  # noqa: BLE001 - degradation must be total
            logger.exception(
                "ai_section_failed", extra={"section": method_name,
                                            "error_type": type(exc).__name__}
            )

        fallback: Callable[[AIPayload], Awaitable[AIResponse]] = getattr(
            MockProvider(), method_name
        )
        response = await fallback(payload)
        return AIResponse(
            content=response.content,
            structured=response.structured,
            provider=response.provider,
            model=response.model,
            prompt_version=response.prompt_version,
            is_fallback=True,
            latency_ms=response.latency_ms,
            meta={"degraded_from": provider.name},
        )

    async def _persist(
        self, analysis_run_id: uuid.UUID, insight_type: InsightType, response: AIResponse
    ) -> AIInsight:
        insight = AIInsight(
            analysis_run_id=analysis_run_id,
            insight_type=insight_type,
            content=response.content,
            structured=response.structured,
            provider=response.provider,
            model=response.model,
            prompt_version=response.prompt_version,
            is_fallback=response.is_fallback,
            tokens_prompt=response.tokens_prompt,
            tokens_completion=response.tokens_completion,
            latency_ms=response.latency_ms,
        )
        return await self.insights.add(insight)

    @staticmethod
    def _bundle(analysis_run_id: uuid.UUID, insights: list[AIInsight]) -> InsightBundle:
        by_type = {insight.insight_type: InsightOut.model_validate(insight)
                   for insight in insights}
        degraded = any(insight.is_fallback for insight in insights)
        provider = insights[0].provider if insights else "unknown"
        model = insights[0].model if insights else "unknown"

        return InsightBundle(
            analysis_run_id=analysis_run_id,
            provider=provider,
            model=model,
            degraded=degraded,
            degraded_reason=(
                "Narrative was produced by the built-in offline analyst rather than a "
                "language model. Configure GROK_API_KEY for AI-written insight."
                if degraded
                else None
            ),
            executive_summary=by_type.get(InsightType.EXECUTIVE_SUMMARY),
            root_cause=by_type.get(InsightType.ROOT_CAUSE),
            recommendations=by_type.get(InsightType.RECOMMENDATIONS),
            risks=by_type.get(InsightType.RISKS),
            generated_at=datetime.now(UTC),
        )


__all__ = ["AIService"]
